package TugasAkhir;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;






/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author KOKOM
 */
public class Form_Login extends javax.swing.JFrame {

    Connection conn;
    Statement st;
    ResultSet rs;


    /**
     * Creates new form Form_Login
     */
    public Form_Login() {
        initComponents();
            setLocationRelativeTo(this);
            setTitle("Sistem Informasi Tabungan Siswa");
        
            //membuat koneksi
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/tabungan";
            String user = "root";
            String pwd = "";

            conn = (Connection) DriverManager.getConnection(url, user, pwd);
            //  System.out.println("Terkoneksi DB");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Terkoneksi Dengan DB Karena :" + e,
                    "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
            System.out.println("Error :" + e);
        }
        //end membuat koneksi
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        loginForm = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        username = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txt_login = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_coins_82px_3.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 300));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_sort_up_filled_50px.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 340, 30));

        loginForm.setBackground(new java.awt.Color(255, 255, 255));
        loginForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/kh12.png"))); // NOI18N
        loginForm.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 302));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_lock_26px.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        loginForm.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 30, -1));

        password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password.setText("password");
        password.setBorder(null);
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordMouseClicked(evt);
            }
        });
        loginForm.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 250, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_edit_message_24px.png"))); // NOI18N
        loginForm.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 30, 20));
        loginForm.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 250, 20));

        username.setFont(new java.awt.Font("Berlin Sans FB", 0, 17)); // NOI18N
        username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        username.setText("username");
        username.setBorder(null);
        username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameMouseClicked(evt);
            }
        });
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        loginForm.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 250, 40));
        loginForm.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 250, -1));

        txt_login.setFont(new java.awt.Font("Berlin Sans FB", 0, 17)); // NOI18N
        txt_login.setForeground(new java.awt.Color(255, 255, 255));
        txt_login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_login.setText("Login");
        txt_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_loginMouseClicked(evt);
            }
        });
        loginForm.add(txt_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 250, 40));

        jPanel1.setBackground(new java.awt.Color(51, 153, 51));
        loginForm.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 250, 40));

        getContentPane().add(loginForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void txt_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_loginMouseClicked
        // TODO add your handling code here:
        try {
            String query = "select * from pegawai where id_petugas='" + username.getText() + "' and password='" + password.getText() + "'";
            st = (Statement) conn.createStatement();
            rs = st.executeQuery(query);
            if (rs.next()) {
                String id_petugas = rs.getString("id_petugas");
                String jabatan = rs.getString("jabatan");
                if (jabatan.equals("Admin")) {
                    new form_main().setVisible(true);
                    this.setVisible(false);
                
                } else {
                    JOptionPane.showMessageDialog(null, "Maaf USER ID dan PASSWORD Tidak Dikenali", "Pesan", JOptionPane.WARNING_MESSAGE);
                }
            } else { //jika user id dan password tidakditemukan
                JOptionPane.showMessageDialog(this, "Maaf ID atau Password salah","Warning",JOptionPane.WARNING_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error at : " + e, "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
        }
    
    }//GEN-LAST:event_txt_loginMouseClicked

    private void usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameMouseClicked
        // TODO add your handling code here:
        username.setText("");
    }//GEN-LAST:event_usernameMouseClicked

    private void passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseClicked
        // TODO add your handling code here:
        password.setText("");
    }//GEN-LAST:event_passwordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel loginForm;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel txt_login;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
